### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Victoria",
  "email": "victoria@example.com",
  "password": "purple",
  "password_confirmation": "purple"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "victoria@example.com",
  "password": "purple"
}

